services:
  - type: web
    name: odoo
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    disk:
      name: odoo-data
      mountPath: /var/lib/odoo
      sizeGB: 10
    envVars:
      - key: ADMIN_PASSWORD
        generateValue: true
      # Database connection values - you'll need to replace these with your actual values
      - key: DB_HOST
        value: "dpg-your-db-host.region.postgres.render.com"
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: "odoo_user"
      - key: DB_PASSWORD
        sync: false  # Prevents the value from appearing in logs
        value: "your-db-password"
      - key: DB_NAME
        value: "postgres"
      # Additional configuration
      - key: ADDONS_PATH
        value: "/mnt/extra-addons"
      - key: DATA_DIR
        value: "/var/lib/odoo"
    ports:
      - port: 8069
    healthCheck:
      path: /web/health
      interval: 300s
      timeout: 10s