services:
  - type: web
    name: odoo
    env: docker
    dockerfilePath: ./Dockerfile
    disk:
      name: odoo-data
      mountPath: /var/lib/odoo
      sizeGB: 10
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: odoo-db
          property: host
      - key: DATABASE_USER
        fromDatabase:
          name: odoo-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: odoo-db
          property: password
      - key: ADMIN_PASSWORD
        generateValue: true

databases:
  - name: odoo-db
    databaseName: odoo
    plan: standard
