services:
  - type: web
    name: odoo
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    disk:
      name: odoo-data
      mountPath: /var/lib/odoo
      sizeGB: 10
    envVars:
      - key: ADMIN_PASSWORD
        generateValue: true
      # Database connection details (example - replace with your actual values)
      - key: DB_HOST
        value: "dpg-clk7vqug1b2c73dh9uu0-a"  # Copy the hostname part only
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: "postgres"    # Something like 'odoo_user_xt91'
      - key: DB_PASSWORD
        sync: false
        value: "xyz123..."   # A long string like 'p4ssw0rd123xyz...'
      - key: DB_NAME
        value: "odoo_db"     # Something like 'odoo_db_12ab'
    ports:
      - port: 8069
    healthCheck:
      path: /web/health
      interval: 300s
      timeout: 10s