services:
  - type: web
    name: odoo
    env: docker
    plan: standard
    region: ohio
    dockerfilePath: ./Dockerfile
    disk:
      name: odoo-data
      mountPath: /var/lib/odoo
      sizeGB: 10
    envVars:
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: DB_HOST
        sync: false
        value: "dpg-xxxx-xxxx.region.postgres.render.com"  # Your database host
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        sync: false
        value: "odoo_user"
      - key: DB_PASSWORD
        sync: false
        value: "xxx"
      - key: DB_NAME
        value: "odoo"
      - key: PORT
        value: "8069"
    ports:
      - port: 8069        # Added explicit port
        protocol: TCP     # Specify protocol
    healthCheck:
      path: /web/health
      interval: 300s
      timeout: 10s
    startCommand: odoo --http-port=8069 --database odoo --db_host $DB