services:
  - type: web
    name: odoo
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    disk:
      name: odoo-data
      mountPath: /var/lib/odoo
      sizeGB: 10
    envVars:
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: odoo-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: odoo-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: odoo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: odoo-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: odoo-db
          property: database
    ports:
      - port: 8069

databases:
  - name: odoo-db
    databaseName: odoo
    user: odoo_user
    plan: starter