services:
  - type: web
    name: odoo
    env: docker
    plan: standard
    region: ohio  # or your preferred region
    dockerfilePath: ./Dockerfile
    disk:
      name: odoo-data
      mountPath: /var/lib/odoo
      sizeGB: 10
    envVars:
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: DB_HOST
        sync: false
        value: "dpg-xxxx-xxxx.region.postgres.render.com"  # You'll get this from Render
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        sync: false
        value: "odoo_user"  # Your database user
      - key: DB_PASSWORD
        sync: false
        value: "xxx"  # Your database password
      - key: DB_NAME
        value: "odoo"
      - key: CREATE_DB
        value: "true"
    healthCheck:
      path: /web/health
      interval: 300s
      timeout: 10s
    startCommand: odoo --database odoo --db_host $DB_HOST --db_port $DB_PORT --db_user $DB_USER --db_password $DB_PASSWORD

databases:
  - name: odoo-db
    plan: starter
    databaseName: odoo
    user: odoo_user
    ipAllowList: [] # only allow internal connections