services:
  - type: web
    name: odoo
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    disk:
      name: odoo-data
      mountPath: /var/lib/odoo
      sizeGB: 10
    envVars:
      - key: ADMIN_PASSWORD
        generateValue: true
      # Replace these values with your actual database connection details
      - key: DB_HOST
        value: "your-db.postgress.render.com"  # Copy from Render dashboard
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: "your_db_user"  # Copy from Render dashboard
      - key: DB_PASSWORD
        sync: false
        value: "your_db_password"  # Copy from Render dashboard
      - key: DB_NAME
        value: "your_db_name"  # Copy from Render dashboard
    ports:
      - port: 8069
    healthCheck:
      path: /web/health
      interval: 300s
      timeout: 10s