version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_PASSWORD=${DB_PASSWORD:-odoo_pw}
      - POSTGRES_USER=${DB_USER:-odoo}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-odoo}"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PORT:-8069}:8069"
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-odoo}
      - DB_PASSWORD=${DB_PASSWORD:-odoo_pw}
      - ADDONS_PATH=${ADDONS_PATH:-/mnt/extra-addons}
      - DATA_DIR=${DATA_DIR:-/var/lib/odoo}
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    command: ["odoo", "--database", "odoo", "-i", "base"]   # Added -i base flag to initialize

volumes:
  odoo-db-data:
  odoo-web-data: